language: php

notifications:
  email: false

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  global:
    - NO_INTERACTION=1

before_script:
  - phpize
  - ./configure 
  - make

script: REPORT_EXIT_STATUS=1 php run-tests.php -p `which php` --show-diff -d extension=`pwd`/.libs/algoweb.so -q

after_failure:  for f in tests/*.diff; do diff --old-group-format=$'\e[0;31m%<\e[0m' --new-group-format=$'\e[0;31m%>\e[0m' --unchanged-group-format=$'\e[0;32m%=\e[0m' -Nar "${f/diff/exp}" "${f/diff/out}"; done
